codecov:
  branch: master
coverage:
  precision: 2
  round: down
  range: "80...100"
  status:
    project:
      default:
        target: 75
        threshold: 3.00
    patch:
      default:
        target: 75
        threshold: 3.00
comment: false